apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: "mongo-express"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: "admin"
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: password
          - name: ME_CONFIG_MONGODB_URL
            value: mongodb://admin:password@mongo:27017/?authSource=admin
        ports:
          - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      name: main-port
      port: 8082
      targetPort: 8081